# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  melange = {
    pname = "melange";
    version = "ce42f6b629beeaa00591ba73a77d3eeac4cf28ce";
    src = fetchFromGitHub {
      owner = "savq";
      repo = "melange-nvim";
      rev = "ce42f6b629beeaa00591ba73a77d3eeac4cf28ce";
      fetchSubmodules = false;
      sha256 = "sha256-4WeIgkbc9RxGB8NqLc/Z12OxtK+v8qbQ03T1pjJ3HAE=";
    };
    date = "2025-06-16";
  };
}
