# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  melange = {
    pname = "melange";
    version = "a51c6faa4fb09331382f87be99f71a8aa48dd422";
    src = fetchFromGitHub {
      owner = "savq";
      repo = "melange-nvim";
      rev = "a51c6faa4fb09331382f87be99f71a8aa48dd422";
      fetchSubmodules = false;
      sha256 = "sha256-qVnr0Rwqqq+wQbOf2yTAS+paB5g2Jp5uvqHwT2uQgow=";
    };
    date = "2025-06-01";
  };
}
