# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  melange = {
    pname = "melange";
    version = "c8266cfea088f4e92eac6026d61759ecc0ce6fab";
    src = fetchFromGitHub {
      owner = "savq";
      repo = "melange-nvim";
      rev = "c8266cfea088f4e92eac6026d61759ecc0ce6fab";
      fetchSubmodules = false;
      sha256 = "sha256-+O84Iep2xv3O8J+oXFTPJomw3HKgltpFO+ucle0DACs=";
    };
    date = "2025-06-08";
  };
}
