[metadata]
name = "bash-history"
description = "Select from your bash history"
requirements = ["bash"]

[source]
# `history` can't be used outside of an interactive bash?
# `awk` to remove duplicates without changing the original order.
command = "sed '1!G;h;$!d' ${HISTFILE:-${HOME}/.bash_history} | awk '!seen[$0]++'"
