[metadata]
name = "buku"
description = "Select buku bookmarks"
requirements = ["buku"]

[source]
command = "buku --nostdin --print --format 4"
display = "[{split:\t:2}] {split:\t:3} {split:\t:1}"
output = "{split:\t:1}"

[preview]
command = "buku --nostdin --print {split:\t:0}"

[ui.preview_panel]
header = "[{split:\t:2}]"
scrollbar = false

[actions.view]
description = "Open seleected bookmarks in browser"
command = "buku --nostdin --open {split:\n:..|map:{split:\t:0}|join: }"
separator = "\n"
# Join the multiple selections with "\n", split them into a list, select the id
# for each item, and finally join the ids together.

[keybindings]
ctrl-e = "actions:view"
