[metadata]
name = "files"
description = "A channel to select files and directories"
requirements = ["fd", "bat"]

[source]
command = "fd --type file"

[preview]
command = "bat --number --color=always '{}'"

[ui.preview_panel]
size = 70
scrollbar = true

[actions.edit]
description = "Edit selected files"
command = "$EDITOR {}"
mode = "execute"

[keybindings]
enter = "actions:edit"
ctrl-s = "actions:edit"
ctrl-v = "actions:edit"
ctrl-x = "actions:edit"
