[metadata]
name = "text"
description = "Find files with specific content"
requirements = ["rg", "bat"]

[source]
command = "rg . --no-heading --line-number --color=never"
output = '{split:\::..2}'

[preview]
command = "bat -n --color=always '{split:\\::0}'"
offset = '{split:\::1}'

[ui.preview_panel]
header = '{split:\::..2}'

[actions.edit]
description = "Edit selected files"
command = '$EDITOR +{split:\::1} {split:\::0}'
mode = "execute"

[keybindings]
enter = "actions:edit"
