[[sources]]
title = "Phoronix"
url = "https://www.phoronix.com/rss.php"
tags = ["linux"]

[[sources]]
title = "Kagi Small Web - Appreciated"
url = "https://kagi.com/smallweb/appreciated"
tags = ["general"]

[[sources]]
title = "Kagi Small Web - Code"
url = "https://kagi.com/api/v1/smallweb/feed/?gh"
tags = ["tech"]

[[sources]]
title = "AI News"
url = "https://news.smol.ai/rss.xml"
tags = ["AI"]

[[sources]]
title = "Hugging Face - Blog"
url = "https://huggingface.co/blog/feed.xml"
tags = ["AI"]

[[sources]]
title = "Google Research"
url = "https://research.google/blog/rss/"
tags = ["AI"]

[[sources]]
title = "Apple Machine Learning"
url = "https://machinelearning.apple.com/rss.xml"
tags = ["AI"]

[[sources]]
title = "Paper With Code - Trending"
url = "https://us-east1-ml-feeds.cloudfunctions.net/pwc/trending"
tags = ["AI"]

[[sources]]
title = "Paper With Code - Latest"
url = "https://us-east1-ml-feeds.cloudfunctions.net/pwc/latest"
tags = ["AI"]

[[sources]]
title = "Emergent Mind"
url = "https://www.emergentmind.com/feeds/rss"
tags = ["AI"]

[[sources]]
title = "Pierrot LC"
url = "https://pierrot-lc.dev/feed.xml"
tags = ["debug"]

[[sources]]
title = "Pierrot LC - Journal"
url = "https://pierrot-lc.dev/phd-journal/feed.xml"
tags = ["debug"]
