# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  catppuccin = {
    pname = "catppuccin";
    version = "6810349b28055dce54076712fc05fc68da4b8ec0";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "bat";
      rev = "6810349b28055dce54076712fc05fc68da4b8ec0";
      fetchSubmodules = false;
      sha256 = "sha256-lJapSgRVENTrbmpVyn+UQabC9fpV1G1e+CdlJ090uvg=";
    };
    date = "2025-06-29";
  };
  rose-pine = {
    pname = "rose-pine";
    version = "23bb25b9c421cdc9ea89ff3ad3825840cd19d65d";
    src = fetchFromGitHub {
      owner = "rose-pine";
      repo = "tm-theme";
      rev = "23bb25b9c421cdc9ea89ff3ad3825840cd19d65d";
      fetchSubmodules = false;
      sha256 = "sha256-GUFdv5V5OZ2PG+gfsbiohMT23LWsrZda34ReHBr2Xy0=";
    };
    date = "2026-03-08";
  };
}
