# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  catppuccin = {
    pname = "catppuccin";
    version = "6810349b28055dce54076712fc05fc68da4b8ec0";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "bat";
      rev = "6810349b28055dce54076712fc05fc68da4b8ec0";
      fetchSubmodules = false;
      sha256 = "sha256-lJapSgRVENTrbmpVyn+UQabC9fpV1G1e+CdlJ090uvg=";
    };
    date = "2025-06-29";
  };
  rose-pine = {
    pname = "rose-pine";
    version = "c4cab0c431f55a3c4f9897407b7bdad363bbb862";
    src = fetchFromGitHub {
      owner = "rose-pine";
      repo = "tm-theme";
      rev = "c4cab0c431f55a3c4f9897407b7bdad363bbb862";
      fetchSubmodules = false;
      sha256 = "sha256-maQp4QTJOlK24eid7mUsoS7kc8P0gerKcbvNaxO8Mic=";
    };
    date = "2025-03-29";
  };
}
