# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  catppuccin = {
    pname = "catppuccin";
    version = "6810349b28055dce54076712fc05fc68da4b8ec0";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "bat";
      rev = "6810349b28055dce54076712fc05fc68da4b8ec0";
      fetchSubmodules = false;
      sha256 = "sha256-lJapSgRVENTrbmpVyn+UQabC9fpV1G1e+CdlJ090uvg=";
    };
    date = "2025-06-29";
  };
  rose-pine = {
    pname = "rose-pine";
    version = "6d556734541ccb04172e81fd58de4a35fff72d19";
    src = fetchFromGitHub {
      owner = "rose-pine";
      repo = "tm-theme";
      rev = "6d556734541ccb04172e81fd58de4a35fff72d19";
      fetchSubmodules = false;
      sha256 = "sha256-5+fG21KbB7bdPvszkz9Ftl6fCDGs17fJNTAXFRFWZGo=";
    };
    date = "2026-06-22";
  };
}
