[[sources]]
title = "Knowable Magazine"
url = "https://knowablemagazine.org/rss"
tags = ["general"]

[[sources]]
title = "Kagi Small Web - Appreciated"
url = "https://kagi.com/smallweb/appreciated"
tags = ["general"]

[[sources]]
title = "Tedium"
url = "https://feed.tedium.co/"
tags = ["general"]

[[sources]]
title = "Phoronix"
url = "https://www.phoronix.com/rss.php"
tags = ["linux"]

[[sources]]
title = "The Verge"
url = "https://www.theverge.com/rss/index.xml"
tags = ["tech"]

[[sources]]
title = "Tech Crunch"
url = "https://techcrunch.com/feed/"
tags = ["tech"]

[[sources]]
title = "Ars Technica"
url = "http://feeds.arstechnica.com/arstechnica/index"
tags = ["tech"]

[[sources]]
title = "Kagi Small Web - Code"
url = "https://kagi.com/api/v1/smallweb/feed/?gh"
tags = ["tech"]

[[sources]]
title = "AI News"
url = "https://buttondown.email/ainews/rss"
tags = ["AI"]

[[sources]]
title = "Apple Machine Learning"
url = "https://machinelearning.apple.com/rss.xml"
tags = ["AI"]

[[sources]]
title = "Paper With Code - Trending"
url = "https://us-east1-ml-feeds.cloudfunctions.net/pwc/trending"
tags = ["AI"]

[[sources]]
title = "Paper With Code - Latest"
url = "https://us-east1-ml-feeds.cloudfunctions.net/pwc/latest"
tags = ["AI"]
