# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  catppuccin = {
    pname = "catppuccin";
    version = "82e7ca555f805b53d2b377390e4ab38c20282e83";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "bat";
      rev = "82e7ca555f805b53d2b377390e4ab38c20282e83";
      fetchSubmodules = false;
      sha256 = "sha256-/Ob9iCVyjJDBCXlss9KwFQTuxybmSSzYRBZxOT10PZg=";
    };
    date = "2024-07-20";
  };
  everforest = {
    pname = "everforest";
    version = "aa1850676e2c2908e7c5cf5ea7863b130fd65016";
    src = fetchFromGitHub {
      owner = "mhanberg";
      repo = "everforest-textmate";
      rev = "aa1850676e2c2908e7c5cf5ea7863b130fd65016";
      fetchSubmodules = false;
      sha256 = "sha256-4GexSj/T+FKsa98kmKfninJMdFKHgQyZFQGVNBFYIuc=";
    };
    date = "2023-02-03";
  };
  kanagawa = {
    pname = "kanagawa";
    version = "e5f7b8a804360f0a48e40d0083a97193ee4fcc87";
    src = fetchFromGitHub {
      owner = "rebelot";
      repo = "kanagawa.nvim";
      rev = "e5f7b8a804360f0a48e40d0083a97193ee4fcc87";
      fetchSubmodules = false;
      sha256 = "sha256-FnwqqF/jtCgfmjIIR70xx8kL5oAqonrbDEGNw0sixoA=";
    };
    date = "2024-07-03";
  };
  rose-pine = {
    pname = "rose-pine";
    version = "c4235f9a65fd180ac0f5e4396e3a86e21a0884ec";
    src = fetchFromGitHub {
      owner = "rose-pine";
      repo = "tm-theme";
      rev = "c4235f9a65fd180ac0f5e4396e3a86e21a0884ec";
      fetchSubmodules = false;
      sha256 = "sha256-jji8WOKDkzAq8K+uSZAziMULI8Kh7e96cBRimGvIYKY=";
    };
    date = "2024-04-23";
  };
}
